import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased max-w-4xl flex flex-col h-screen border-x mx-auto`}
      >
        <header className="h-12 p-2 items-center flex">
          <p className="font-semibold">Dana valencia</p>
        </header>
        {children}
      </body>
    </html>
  );
}
